// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyjhNl8N0K5xsItpK5o8yr4DMX9xKSoIs',
    appId: '1:383938853899:web:282ada5190613e7b101b0e',
    messagingSenderId: '383938853899',
    projectId: 'flappygoose',
    authDomain: 'flappygoose.firebaseapp.com',
    storageBucket: 'flappygoose.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv7XsIKbFFPEc66cs08w4_Id-Xr8fahXA',
    appId: '1:383938853899:android:2021ec211d8b8d18101b0e',
    messagingSenderId: '383938853899',
    projectId: 'flappygoose',
    storageBucket: 'flappygoose.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5qGY_lcq_9EzCIL-RLffcIrSx76SfeE',
    appId: '1:383938853899:ios:1948fa42326be2ae101b0e',
    messagingSenderId: '383938853899',
    projectId: 'flappygoose',
    storageBucket: 'flappygoose.firebasestorage.app',
    iosBundleId: 'com.example.flappyBird',
  );

}